---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: byoc-fluentbit-s3
  namespace: byoc-fluentbit-s3
spec:
  encryptedData:
    accessKeyId: AgCio4GXXi5P7TKc0+mEo6w7p1IBQgl/Sy3En3n+87PRdsx+omKTCJ5EiVFELDf7h4EMI7jv4bpb//ps9BBNeT4aIgV2DXp6IQaOX0rSnMGcFgTdPRhbtJCsQeOO1coioHYkvvNUTpFXzvq5TGaU4WZcUbd2sixLtjd88nDmP0ICBkY3Y5jgHFWSnUJXvz02qDJ/FQaxOhC0g2uPmSBcfEDgV0zniAJoqoQU1IVn0Swa/NBWIzp9tmLYt5RQDS4INVZprRrxGudfcbjIe+/B/R3gEeEn32NQ8VHPCOXWpuU7Q39L8pnaKZRO78DnhTfetg8yuvVL7Daf3FFzGLZJ/TmN3q5JMBCUsokLrmoklBwV5t9LtUyMAIutYyqk7sV3pIFQfkH83JTA3z0X8OxzEDng7H8e/MdxOlS/ehV4RDmLMiZDWEFPLMUv8FBi8X6k1ADOUDt6K95NUZd8UVmUNeOUBl+ZXnLYXrBt2W+/CgZOWXFAQTaja+P+xrce5e/jrE067zKzjvTfJ/q70vcgbHFamHWzTzZxW6gJfcOS6laDipZjUSqXCJbrrZg0HDdKUsovZ3iJT5JaOaF+4Oy7oXsjDBDxB/SB5gpYBewG/Y8QuTXKhhA/AghkmYPgLpZO4nn44OOxe2Nt1XGlVfj9v7sa6KIc0YWkvaIrUMHWwlo1EBp/lI2zb7pbJTZ2VXMT/SW8tbOPBui5S8DB5mWIJ5yAap9nkw==
    secretAccessKey: AgAG9hLwXzW5GuLdCJGlcXiIOVcD1/wGgBdtJ9Q/39+Dix2XaNsGAFuyHxVKTCyuxd2wil1WG3sfDpf0ki3ey7FzPo3VEaVl8/SZror1h4AkS3vZ1Itk20/I2mc3ee19nyBdTtx6K+Ihp+ZF2/Y4e2rlr8g2BrNYXaeS8JC7g5lPSXJ46EiBXvB2U4NtXxyfPang3JCvbDaHoCPuMP5Dk9yJB2C0JeHV2ggCdF1c1o6gXKLp8AfmJc0SYBSIm3XnCN4Y4XSkGaYP18TZnHepf6HZEykq0DzirM/iULPMaFGq7y+lRGCD3fBrzhHRnPpOs4qRX3F0tgpSyutDAt5nLC3YeRBxbCeicFml5vVhOijj1PWxBWktjhZ+77/Ckp7ioZv7ryULHMT4iboc5F5xnbRH3Zz07yCiijxAOfUD5Jaf7VHWZnjpqV29AvY2v4DngmDLX1PmmOhY1hfncjCOf5Sj9wb+mPkQ6gA1XxQ1oxoZn5RY4B1DFhTSMLLPxJ59sb1VeHThArxw08YiwM9hK4b5dta6gcQeNB1d8vltUUygMmte0J3gi5rodgdS7OWDRLfIipJp0fiq9WxtlZFV8QiR8njpuyQ3a6godKONa828TuT4nV+/8i6IhRJ44dcXi1yQIJHI+94lW5pFTRK5ShVgSbRq4150jVDc7HFbEb0dlFzlMeh3Ef/uNpEXJB2VTh9BnqC2zZ/gb0Ldq9TWloPWOSW6TVyYiA3T8ZB8ZgIu871peWfYeeG0
  template:
    metadata:
      name: byoc-fluentbit-s3
      namespace: byoc-fluentbit-s3
    type: Opaque
