---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: byoc-azureblob
  namespace: byoc-azureblob
spec:
  encryptedData:
    connectionString: AgAVItEFn4J/ey3G+FoY67HdX865C41TI2Xiw4zQzZvatE1kRKZR6qEQTdiw3qlDh3MGqqMHbNEmf0B+yyxaLBa6nLgADgwkfHTUKTi8eXkPsefI6pT6xpDhnKWTd1tU4VmLmfKOCoMrJaHcLJsSCR/lS4xaJT/VAEeZ3aw0shps4G8ZO+TrYJC3GtMHMRPp88N7vQJSiWAZ3YyjrFHb3g1QY/Yznf8LqBi0zFc7q7je7iHL15NOUE/z8qhvDjSBQ17PkT94DuHnHP5uyczpO+qKH/DvFA9aDrShhv6p8vrHmYA3JvS5WxUG1Ldqzf1TyJSAtBm58BGEcHPvYaRtMO3lQFdohTYdR1IBNqS9qVp4JSow9VY4+4w5LLcUypRWI6uEP38aL+Ms9cHWqYX4GRuJeU5IbRm7kxgii7AiyAfkh1Yls1kWuC8z5RM16ei4j81DZo4030sPuHine9wOo5FLsHPXYliZnmPIeiqcBZFq2SmzuB13rRvsCF+wJARGnXKFtMlixIWZIKqgvljJHCQKMDkmHqWFFS5o5JmzMEQo5s/6xhQdbr/QBRzhELxEApcmHkcVr3iq6ylYkVDskb5pBFNOoIaI1+eqazHDlwO8geKjOJsO0WRSgbenSL8HpYkeQHgIkqmpWTLioBmLICYIoV6aHuEIHDHSRs1YKBz///OaqfOZbEkrtZwkdWCrAW4eOSNCDmgH98nPsnBXTf64xnTxYFVyhN4AMp16+4oDX2rSwv0PcwlcAWllXniQKCE8sNNU3S0Cu+dwiMYWiA+OE5cGeac7Ahi28fkl+rIkJ6L3w2/vkIOSACEzn6ByNMOl1aUMwllMZI84nPykeuYkyYwR2Nh7l2ob3w+tG0NNnreR5lVFRaeCjsXv0iGbSWW8d1YHRfRf21CLWBPbh3oO/AwJv+MDZC71NwjJVyTFGYjhgkgwh+dyDqBRO+yWhQYCRIAMc00ayC8xbIHbWgeAgGyDFM+p/zgqotUGeCzVDaTs23uKwwjirBdsK/EoeDdrjkNGmZVSZvs6ogeo70HAnEiEHcRPr3hI4DhaZlS6E4KM6m6OChrHKiFxLj3nUINYrRDnmHlH8/41Vi2GfhbMoj/aNHnzmCysnDlKhmG6FhH1IuAQTJxv60Wq6JfnCpDmWymES7hOi0f1lCa5BY8b9XWEy6CLsBM3GEJo/jQx5A9RGwHLppN1RsGgyA9qYCvlvacx0jr2rBANujncaORUFq6TJdFnhSBISuWQSrQ/5/zhU1SBt7/zzfB//TI=
  template:
    metadata:
      name: byoc-azureblob
      namespace: byoc-azureblob
    type: Opaque
