---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: byoc-fluentbit-gcs
  namespace: byoc-fluentbit
spec:
  encryptedData:
    accessKeyId: AgBwpvmDYTJxZ34WqJF6llHbD2pVWZpyphdkt22QvOWXPkb961xPYin0a07ihsSaP8wTjckUUdYhuEOZXsIWafrFggPqdJ5iGK6kQvcdrT/teegd81KoKU7jYLZ9eD0lnR/wfShD+1EM9FF+7haSpcgrPy6wxmXLBhSruZxObWVu0+5RZsW0ICMG1FtPZBxL/2kD0yfp+k7sNi4Nvw9wA9gpmkcWdQIxKrj9t3Xuj1314IO2Bf+oo9v4faNryhR6f1kJa/msNVDF+2tetld1Qq/gpsO3EgLj0dZ4k8sm/9B64bKGxDi/DKrkCd1Lxtp/KYwPc6emgJULY1szocMeimthYEuWRaH3CdOgINJPuPtQX1bM7PNIMpJBd7TetUW6CdgExNWFpcGc1u99Y+gSL3hyLxZBemrgBnJANhXPRnppys4bUkSkzEKZj/RLeGiCMqdMXr9FH+deb2SroMjqaRYcJ7DuEXdxj8hJfVgVeQZH8OG0Sz4ixdxLd3DFPdnr6gGvA7gd9coXXzLXF7PhRn401CfkVXsXstCOgypRg2Kc6bEg773mwGWeYjAUAndBm2W24mvCeiRlwhD44kMGzjSm0f4r/6rt6ydYYgoo7LoOI7EiExzob98J5TlkKd+em+EdhEUmw7cCwCE4sbboZSysdUk2A2H6o0Bne61NSEWYeOMhlnL6FsWP8Ie85Jial13Jv84PoIbnrbMkzzi29/E1NN7JIMhx/fqHQmFvfBB2ChRlWOweHWJ6Nxw1hAfWalLqbvwn1J83VwwGQjjy
    secretAccessKey: AgBa0d/DVUvLRBU2pJYbyvshcrgsx0SuZSBJRBbHNtWCm1lRR3MoJsBFROVpqXFtU/ZXvJClmWdcSOSt1dszoHCBdmWIkTGVyrf7vlzJFJdME7bfT3YJdErT1GUCOGohHtAqFnQB3juwmtfYy701yC+QZCzbn1QYF46JMJPtIcugk3v7Ns0rKpJN11c3fn0uPZ9rhECGIfrmEKy4RgR6hGMPkJbA6M6VrbctHxLG1EWvyXBhyCM/d6eGMtLO1V0IwnYG0dImM+pOCT8iYEmW4UaP1M8hmaA3taGfSYdQf9hX1lPgnMA5bEPSDewUTq6sRVgnLCIV18vqk9L6CiJh/ED6zy42pMmQnLHbZo5UeI/skS/zlTEvep1UbbtMIZGvG1efsTIoN1dkRiLtaDYOhBVeM2SkKPjGVjO354sW9Q3FUWOCYSLvxrRDW1+dBiqITfYqtD7PKUsp0PEd1FxMwe9NdeWYru46FmpI7ow4YJo+imWR5d3Tghvlf8OVC6mX6Sz1VKrSkQ2LdS2uiI0txC6GEmp3PBqGV5hSVa1m7fT/8AfHZPTLiJPgPZ7Ix4YNP73PdEwKrqWmPHZllCSAaK+pHbEMV/gvEWaZwkZ3mXHDcSsOkgYnlVJZ/o1dbRcNJaIQddi6mOorQ3JfyUlkYakpatIdcD2XlPScyILpO5VRxrTh1HnXOZ8qk1RVjXDDUjiOg6Zn7WBqbcVFlTA+A9HnMF0AGqv0o3BhiZG0y7YtfQgmzCGHP8PN
  template:
    metadata:
      name: byoc-fluentbit-gcs
      namespace: byoc-fluentbit
    type: Opaque
