---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: replay-lab-byoc-s3
  namespace: replay-lab
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgBe3TRBxHNMPOG/DRAtb620nAq/Xli5Iv1M27cQEwW/lI7wvicC0Yb3f0jK+zuOThpIBV1a6QttXWeKJbODS4Juz6gNaxr9z8jjEEXXLZ9cByIt8/0/IskN3OVuFsoNrj9JHRoGurrFWNrq2FZvi+8iRUGP1urO0O2gJWBstH8CpTp4gQsegmtzQXEdb116Eyyj73meTTV0srURnx68gkSjTCDlnNN+UnUmi/M05e+5xQJlkKmoXa79CfJ/QqwAslZw6PEH2BDZs8TU9F9nb8SwD8knnEBkKKW9uHdxRF+1f6HLSht1T5bPDhw99XUuqZc2QoVn0Fs6ml+q8ceMTyrSvO4zhHfWC10o9HYqJXYUwxmX0U4f+iWq/xtWay3jGT0u6ii3NQgpxJVdbibiiq1rrTHBNaVeCzmg7rhQw9w9LznK6Y2WPY5LxAcctII9SNtXA1ymT7bhneKxmJKuA0UB0wJCeIVWnzW/h29PThEsi3BbHrI56aJ8m+ctOHG6ttoXfyY/Vs3bAmsKlZyR6nn5dyQAcvU3RYCLcXspTjRnKOIJBrRGUT2B+XuvEQlfzmremMgjWlaJLNN9rsw3sIusMUwv177zMqHwaxxs7/7F5SF2ugreiA1mhJSCl+Eg1UUI1EHSdZCUuszxXPar2ab1Nvbzp/OAmyOTAR+pbp1MTjfotx1wF2o7sZRhgWDPs3l9I9QSPfb3ewajUdH3m7+tQjYr1w==
    AWS_SECRET_ACCESS_KEY: AgAnBF9Z9XttKZbErr/VhP5u9LQ0rla6ZLJodFH9VWYvL+idwmzT6v6dNYr+GFf2GXJRBMonxzD8tskh0wp/F2PJMK7BHor2mrhpsg94eYxBnfWDCx5lTpfKdF3atRDl2AGyjecXO1nCUzC+4vU2vkh2SidOsc4D3dU110l/7CPSBybZYs+1DDTGCA7ohgxD+4GOda7H5ynNXmIyzSECfZNoBZruWgskGOdDUDuTf3kjJ2abb/ikTfHKc4i7+RlREYAjFWJmIvpldZ+ds96FACZC2czLU9TpCKvV0W3g+PZCPMI1ChfApQRK97GJWAhXR61RU9yN5NhD+8CCftQcls2N+p2WQTGHRCa9GvTJ/1gq3IvvBEX9vWYUV68PEe8J56MmJd5AkCunMlmgYMVJRBeuzw7wPmZHvBD50AKkNZX8sObpNMhM+mBpmUitD/wLqJGoJAg1amd5I/C67HMS0BTKBEON1axavlJQHJYMBrgWsk9XeHoJufg8IxC0xfL4LGLdUwMAeoNt8Fd13mj1yhVzLpmy3KbFjEVFxYSgltrgInymnFTmWIJ5FCHmwYzzCF/8DtdHN1pWE6VfXkdIFUusORx0zZ3eFLl1iCvnVmeThcc4x1M9k5R/U604z/Lh8dD3nF+OLNHeqheUSVi6WfnCoP4D4U7KPrCreBZWyXUGhw69wZBCiPd7NonqtWpZZ4a/glWoAFBqOyornJZJolDUtYl0ilVbaYU9KdrDflpZKTPcbECa/Aqb7i02
  template:
    metadata:
      name: replay-lab-byoc-s3
      namespace: replay-lab
    type: Opaque
