---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: speedscale-apikey
  namespace: speedscale
spec:
  encryptedData:
    SPEEDSCALE_API_KEY: AgBpls5gO0A6Z7lW7vowyFt7viox8fOQQ1wiACT0CjcusIOnGQLRQFyH3PwG/cBNHq1kidiWpbKpwo0XaAdkT1iJ/00eW66u8859gfwk+8DuY2N8da2PceJLdgYjdoQTJsmqXaP6eo0hxD8y0DMRfCFWmOoqzM/1j5IvXvY5WEEkKVXSWxBNg8fmcjXx52A0m0+4p8EyUIKyeF02MyrEeYfnNvxqyyVDvigZWMWlZpExcwc/x9ZMJLOCjEAmNkWEs9zpKwAUevTYVAHjJ2Zp8GE2q74BY+W/i4iAm5DyoRv3oWusSc/+YyGCHseiDSruyAuosoI+GjOlY8zOqgVFvw3rxvraxHqVBY5NR9zYTK2bRfCNw5RkxM9aXpAbXQW7UxrvaTJvCBpiNiiJC7o/ZdE64AqXjT1EusPUCEeIVawUcaaTRzCs03m//f5WKewsQ8Hcsm6NXUOKTY263DrOK3wfAPzcLr0Ue6g/6MZRl5hQys38EnEFORbokNngYHNVLtkv9qjhqeqKli+tAIOG9SojSAAb8TmZAxwfjmvaPZqyFK6eSfGdRxpYZk87PahcLRMvaqUATdZvcovnuHSA5tEjaZnsMic3DcpuQm4qh4g1FKusvOyTHOYPEe+4z+UpHIuhDmadmpPttm04+j2GPe49JR+4lIv3fU6p2uudKowBm72xqIoxQYZmse228JPaOaEVNz57NInvvWuUJ/cKczZ2yTgn/AXufzROAUZ4J7wjximW6nOuo+at/IXuBPA=
    SPEEDSCALE_APP_URL: AgBuATYfs52NcGQQ9CRSOy8PTuetBtk90NauuwR6vpR49WkHwycBOERgDjNRouiQcc+iSx4J8/dN8JSvLqiLMBNZUnDBqJwEzJxQmKI/YuV/F4Hc63WDyyKf7vnmqiuyOJT0zRpfVPPRxb4+HCFHKCd18UjEYXkEqgkifCXKRqbhcTRCKK69VYn5aoPE2mN+HVxCqvtCEOKtpRvIOYo9n7fSZxmaFvg3s9XFbooZerSZ4lPB5PyatPua2uJQXgi8ERyTFKzpxOMIsk9zWJsggkjOGyuW/D3HbkOnCCxvCUgvweIwjPUSeY/8kGm1lrtNASbM/vllTuYsSTS3kyrR0u/CVNZc9KPQ5psiNq1uVeiZgyPEFxHtA5Swt5L9eV/MQihXy/AJpH86dSBjtOp+E0Sxikl1Y7sj2aNm3XmTY9etdZmZy1QHC5UrsHc0NUwZ/j/seqjwsWZzC3xWvzOkAT7fpxf8tJSex/qGgyCwoi4yXVTsqv0gA5U53txGnpUW5tIIETLOUC1ZhbrmAZV6NPlbY0Fybcv/w0aQR3il6DtjYieaUaXw9JGu1p2hEUtZcdCg8dQyL736FpubK4cnUP5oyrqtrDwMVBKs8VkjdsvVzCw1fDfqpPL60/N4+OPPN1PQeF3Hpul8+vfQLKiNKfwyvjIldBegX/9ODw6W7jkpma8ANAE4cUoCZ6NF64qr6blboailE29pvWAUOrKFyhu91+Yoepscow==
  template:
    metadata:
      annotations:
        helm.sh/hook: pre-install
        helm.sh/hook-weight: "3"
        sealedsecrets.bitnami.com/managed: "true"
      labels:
        operator.speedscale.com/managed-by: staging-decoy-0262bd07-cd66-457f-9f08-74e275fe0780
        operator.speedscale.com/shared-inventory: "true"
      name: speedscale-apikey
      namespace: speedscale
    type: Opaque
