apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: byoc-newrelic
resources:
  - collector.yaml
configMapGenerator:
  - name: otel-collector-config
    files:
      - otel.yaml=otel.yaml
