apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: byoc-newrelic
  namespace: byoc-newrelic
spec:
  encryptedData:
    licenseKey: AgBb5OUI8dW5ysOzIDsY/+06Bnb6f82gbmaKY6V55srw6rAWm4rVKONkgXIUutbwH3EwJCQm994vlGbikyEUadcY49s1cI6MYVGWtRaOe+G1YH8QvjikDmo7D3ypmh4I21bOQ9xNuu2nmyEScflKeSza8X6vZhvfuGyN74ejfOmCyxSdg9TxJkHOGF5mbB2vdk+jDb4qe5E4MGZjEsdZCBeN3poWXXZEW//9n73hibjU9KN9pYnll4YUxFmt2VO3zhYrIA8rlBO3NPA5xRerb/01rZPVzMliXA4ANuIheenLcAooGtSsyXq8K3cwO8GVwEcy73IxJaGGDdYQfgJJKlQtNO4FeKVl3wHjTRLkG+1atMRTun9JcYmorm61QAHHVEJj6yh4Ny6L5ZjFWEt3OP9JuGvOxZ1dYd08ASKhrR0yW/O0+62JoSM40pVdkCq0avAqj0ZzpqdbriC4aPn+9F71wrVTxkfOh/6dZY1FpGdtx52zXhk0GXGbkVbtRV4vbC4W4/BlNivUINuyKWJ3bI4XY+3Nsx2kWWVgiV3SSdAgdutiQync3nwCZ4CKSvNr/H/Lt2jahN7H6fRe3wyEaRmYx2L97Pxu0kaN4HGbCLehrNz++fuIBiOBU6VracPyEx8Z5AuOTilnyMKauj1jsoBQAnu7r2uJ3XOIy9piiwjfBLgL27dgby54C/Uvtxp6HR/F2ETlUUcx1pjtQLoOeXcthI8lVsWMtFPod/ovfq1m339vSFs3jV5V
  template:
    metadata:
      name: byoc-newrelic
      namespace: byoc-newrelic
