apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
resources:
  - router.yaml
configMapGenerator:
  - name: partner-trace-router-config
    files:
      - otel.yaml=otel.yaml
