apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: byoc-elasticsearch
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/speedscale/speedscale-byoc
    targetRevision: HEAD
    path: charts/elasticsearch
    helm:
      values: |
        elasticsearch:
          javaOpts: "-Xms256m -Xmx256m"
  destination:
    server: https://kubernetes.default.svc
    namespace: byoc-elasticsearch
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
