apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: byoc-azureblob
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/speedscale/speedscale-byoc
    targetRevision: HEAD
    path: charts/azureblob
    helm:
      values: |
        azure:
          url: https://speedscalebyoc.blob.core.windows.net/
          container: byoc
          connectionStringSecret: byoc-azureblob
  destination:
    server: https://kubernetes.default.svc
    namespace: byoc-azureblob
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
