apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: byoc-grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/speedscale/speedscale-byoc
    targetRevision: HEAD
    path: charts/grafana
  destination:
    server: https://kubernetes.default.svc
    namespace: byoc-grafana
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
