apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: byoc-s3-dev-decoy
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/speedscale/speedscale-byoc
    targetRevision: main
    path: charts/fluentbit-s3
    helm:
      values: |
        s3:
          bucket: do-nyc1-dev-decoy-byoc
          region: nyc3
          prefix: byoc
          endpoint: https://nyc3.digitaloceanspaces.com
          forcePathStyle: true
          credentialsSecret: byoc-s3
        layout:
          enabled: true
          workloads:
            - namespace: banking-app
              appLabel: banking-accounts
            - namespace: banking-app
              appLabel: banking-ai
            - namespace: banking-app
              appLabel: banking-fraud
            - namespace: banking-app
              appLabel: banking-frontend
            - namespace: banking-app
              appLabel: banking-gateway
            - namespace: banking-app
              appLabel: banking-notification
            - namespace: banking-app
              appLabel: banking-transactions
            - namespace: banking-app
              appLabel: banking-user
        irsa:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: byoc-s3
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
