apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  project: default
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    chart: istiod
    targetRevision: "1.28.1"
    helm:
      values: |
        meshConfig:
          accessLogFile: /dev/stdout
          defaultProviders:
            tracing:
            - otel
          extensionProviders:
          - name: otel
            opentelemetry:
              service: otel-collector.observability.svc.cluster.local
              port: 4317
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  ignoreDifferences:
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
    jqPathExpressions:
    - .webhooks[].clientConfig.caBundle
    - .webhooks[].failurePolicy
  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    jqPathExpressions:
    - .webhooks[].clientConfig.caBundle
    - .webhooks[].failurePolicy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
