apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: replay-lab
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.com/speedscale/replay-lab.git
    targetRevision: main
    path: deploy/k8s/overlays/dev-decoy
  destination:
    server: https://kubernetes.default.svc
    namespace: replay-lab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
