apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-base-staging-decoy
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    chart: base
    targetRevision: "1.28.1"
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  ignoreDifferences:
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
    jqPathExpressions:
    - .webhooks[].clientConfig.caBundle
    - .webhooks[].failurePolicy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
