apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: partner-telemetry-staging-decoy
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "9"
spec:
  project: default
  source:
    repoURL: https://github.com/speedscale/demo-infra
    targetRevision: main
    path: clusters/staging-decoy/partner-telemetry
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
