apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: speedscale-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://speedscale.github.io/operator-helm/
    chart: speedscale-operator
    targetRevision: "*"
    helm:
      values: |
        apiKeySecret: speedscale-apikey
        appUrl: staging.speedscale.com
        clusterName: staging-decoy
        dlp:
          config: decoy-email-2
          enabled: true
        ebpf:
          enabled: true
        forwarder:
          exporters:
            agent_factory:
              dlp_config_id: standard
              filter_rule: standard
              otel_endpoint: http://agent-factory-intake-api.agent-factory.svc.cluster.local:4317
            byoc_azure:
              dlp_config_id: standard
              filter_rule: standard
              otel_endpoint: http://otel-collector.byoc-azureblob.svc.cluster.local:4317
            byoc_es:
              dlp_config_id: standard
              filter_rule: standard
              otel_endpoint: http://otel-collector.byoc-elasticsearch.svc.cluster.local:4317
            byoc_gcs:
              dlp_config_id: standard
              filter_rule: standard
              otel_endpoint: http://otel-collector.byoc-fluentbit.svc.cluster.local:4317
            byoc_grafana:
              dlp_config_id: standard
              filter_rule: standard
              otel_endpoint: http://otel-collector.byoc-grafana.svc.cluster.local:4317
            byoc_s3:
              dlp_config_id: standard
              filter_rule: standard
              otel_endpoint: http://otel-collector.byoc-fluentbit-s3.svc.cluster.local:4317
          resources:
            limits:
              cpu: "2"
              memory: 1Gi
            requests:
              cpu: 300m
              memory: 512M
        image:
          tag: v2.5.630
          nettap: v0.1.31
        logLevel: debug
  destination:
    server: https://kubernetes.default.svc
    namespace: speedscale
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
