apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: speedscale-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://speedscale.github.io/operator-helm/
    chart: speedscale-operator
    targetRevision: 2.5.630
    helm:
      values: |
        apiKeySecret: speedscale-apikey
        appUrl: staging.speedscale.com
        clusterName: staging-decoy
        dlp:
          config: banking-app-keys
          enabled: true
        ebpf:
          enabled: true
          configuration:
            telemetry:
              enabled: true
        forwarder:
          exporters:
            agent_factory:
              dlp_config_id: banking-app-keys
              filter_rule: standard
              otel_endpoint: http://agent-factory-staging-decoy-intake-api.agent-factory.svc.cluster.local:4317
            byoc_grafana:
              dlp_config_id: banking-app-keys
              filter_rule: standard
              otel_endpoint: http://otel-collector.observability.svc.cluster.local:4317
            byoc_s3:
              dlp_config_id: banking-app-keys
              filter_rule: standard
              otel_endpoint: http://otel-collector.byoc-s3.svc.cluster.local:4317
          resources:
            limits:
              cpu: "2"
              memory: 2Gi
            requests:
              cpu: 300m
              memory: 512M
        logLevel: debug
        operator:
          test_prep_timeout: 20m
  destination:
    server: https://kubernetes.default.svc
    namespace: speedscale
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
