---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: replay-lab-byoc-s3
  namespace: replay-lab
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgBTEKv6qGsOE0EkgTUtP/HfJXDWHXuGtznPH9RjbtzoLNsSPxSOPq+8ChtmneKAyxwjUVoM2rp1cksm88eytUQTCMqw/Ra81dhfuxiHohnEUvkyIiBQ5J78l3HQDBwsfx51g4POo8zcrJiaqA72T/C0XiJ4gQPgqhvzNa/1AUhtfc8OkL1cAO2Dm/LyuiDfIjStUMTwRhXrGITbewWA1ExtQqbUBhGqt88Y4qRYxvNrllRVISE4AZTdAoid65Lmy4Z6FWQCj25r3MIG5DRiqfoR3NGy2izh6O35KZAyUMBtOJ1bP8oq7vQC8gZD3MYdszQE20ieXapZsf9C51FA+PMRKVEyVBNflZU0Iu9KAK82x59EfEQdZn6O3Rk1dW7Iv6ifD1V+ALV/wjOjZaJeF9GTvh5ufyLViQOgVY7e4v1o48lcmdoTKapi640BvQ3f5CNfH+3JO5PirwkbzqU6z0outHA8QydhBWAxnU+B1+3koMjYJCaSDlJlIdDty5v++Qwyofn+cQUqb0BFFcUrsB+ZyYajK7IBpbHPlFeKaHT1qxii1GfcWJkYrJBg9ZERWW2ZM3W6zQdu+YHa3Etg2Yn+EdCKqNMYlNMr6r3j9+yDkyt9/mtbqvBKFIgjbPlIbgSUIZHHUUl+uJoBI3j3C2VR4303B5JodqFHAh2iAo3HdQ98qkRLDhMjhzLfCSXmlklviJT0I9anuvEOYY3rZhh9ghnDsg==
    AWS_SECRET_ACCESS_KEY: AgC13IybHJzw2IQ0fQ5JcB+ALJVL5qCuHCoF4AN9EczGNEMBUeLLSQO5rTZaA30ul5+eWTIWQLOw9xnRIQZ+KBRK0gTp3IeN5mmVy6z30EDALRpMjd8lHBWfW59TflWiSh/c4UOJeEXJxXdhnWFjqrmwlt80AShuPiBHYmVAwWRUme0hnLhIGijVVGWfZwzyxAkbPBLAzRP23S1k+W7qJ1muEtHx/rdAjZdGpm0W+PCSZq3o5utUBRfS1RLLQ+mOr9ljVX4cd5pmCuRGliXgSdDHKOqPP4wG83G0GuCAmAgllfyn9MV9Y3dKKyq7nNoKQM/C/jA4PIHVT1myiKxqohyaqDHIZtuvugOUv7dJePEnvO/r/UjYgO0J2nrhTkwFH+PRZkiRAiWzFwgXdOt8Xl9nVT7zsBGuCwSOIDM1UcLQ958mIsLXd0a7qu/sJnAIEcxFDaN/EQ6B2g+lLmmyRNwH3qsoRGaPlc1JboOYOo24mdObmnV6GL44YA8+H7MH834vM9cpxNHPy7SkeBSqrLcCyNCvOIF3Vi9USBy8rmhi8cjr5D8UGJQa4PfMOxR4eRNNwgHKgZivbIzxUmWjGMzafWU9VyR5mDRyhOGpfYQTaoE8QrsXHJBATeGwfFapRbhyacQEKb2UMkXFp02Wdbeaq4X2C5oXHNaiz6ArxfU7k0YCtrR5ED91IlnakJ0ZfI5vZhAx5ndN5aQEPqfqfUkIgIPlh1E6LX3t5UfxF35h36uZQJ0R48LRu+Mm
  template:
    metadata:
      name: replay-lab-byoc-s3
      namespace: replay-lab
    type: Opaque
