---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: replay-lab-byoc-s3
  namespace: replay-lab
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgAwaU/nmSby590hWuQovv3EGYGwzEhPzXWWn5yZb1MOOIuNodSd7piFisNR7Y7ec7oq3/OuVDbRSBxeu055y6eaHpwAyx1pZk38m6qoPmpTnuO3b5r9lMhGSrW9PXaX1e4iLMJg84mObqm3yRxuEt8mTAjEeJ03UsRYhDtBPr+E5it9Stolvn4r3WsH3SxMaWXoPCgnIKcW8Qf94KIlp+HuIH7isAdsoCOSpWMPBXEekDOvnvyMCpzqAFfpidtaVtaRrQo1q0MHlhZFxzKGZT8IZRX+MTQ0zP1Mjn/LZ7a0TLYzVXWgRqG8fJSFG0OsfwvqVCCoyJatQvIzbMJrfgMCSdgZr3ohKg66pyiSIP+iberE7Y3P+Axwr+y5VLfdc+DJISfk6zWkQPrHmXOr3VsKaEsHDwtWC9jQBOol5CQ5i+N9Zk2ZefJn3xGZDWjjhQj7GiBFkc0UtFnq3Q44CbriKz+Pjix0iJJetLw+WokX/BsrfH52ERRaLrWNFN7rXgBmTJxXEp/+KKhMspOkmX+thZwXZMofRbX25KluCQnrHQ8tqKxqy3Qs9XWsoht3FWlQdzIL97F08ejb1CTDcqgU+e3D9rxVg+bPcavhI2CER2NzJQlEw6as98JSCrkPh3+83Z1SKbT3nrHkIimBTUsvBSYzbREYDi1Zbk1jXbHhpiqePbB211MQa0e9sV01BhO3GuqZj3M/+z2WvMuzaSH/sWhOpQ==
    AWS_SECRET_ACCESS_KEY: AgA/Og2+Tx0jh266Oky6WgndxqDihamdizQbEWKqUbOduBLEOy/6/t5DFieDArLLLc1UwBxBn1fX31Y5VfaCEJuiIdM1MHv2IAp9tOSIkSdNPy6VTLEWXtb1eMO2ImkRipCYpHRZJ7WoJjmntMsOOUmeSObgbuxcWqvvO4lBzdCkknejJl2kJqV4uGExus4G+tSfrAIA7NxYGKgzPp6raZhrSe2swSgJQw2tknECwzNtJKj7tQQGN5d3UTB2TWsTGduq/esZ4FM1uPFqj4hYECDGjpJ2pdS9GOnBaKNpYOy8l89bPKtdUZaIibjafJHpyQxYssxdoORkRdRv/VrhyBFPOnj/6nx+24IxhCEoRz7xRPX7t8HLUHRGhjmHz4pf/wP0870W3N6tHosbGUPBeqKKD5elbT1M+dbApbmq7U8Gf+lz6M4IUBu8Oiwg30cHTzUZ1g6zqhw1t+9ztPTWn8yMGvZSVcMPDjLNZqwr3K7OG+5Y2vYBscsy3E/VtYjjwtge4DIvuOyZsT858k3B0UrsHZ15RwmekFHdMBTs0+7ZlVaSELA1ZkJxaEdM43Aiqv1I6R8ZEQEdep062pg5BLUAZ2zhvubhKAZI+RHhQqnPtwf90vpnuk9zbsr0raU4QBPKr97aL8tV9+iyEgucRoQogugy+84lFvYsme3idTkpN/bP/8P1xJOWVZcKy93WZOZEXJNBCRYuDdjDach9d85AfTW12pXnj2jipoWeY/YLXNDRJx8oUZvgT7Z6
  template:
    metadata:
      name: replay-lab-byoc-s3
      namespace: replay-lab
    type: Opaque
