---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: speedscale-api-key
  namespace: agent-factory
spec:
  encryptedData:
    token: AgAWx4voEff9F9+UDtQDOrSi/a6sfp45BjihPVdNIWTsXWcanxcEI/2PDbZKROX7htPlCqI2dMt3aocnGxLXMcARUrMKFh/qyFilKS+UIlET6lb89f5qWjpJkvJEWfV7sdpQ+ddBHYpZuNM1GiMvXaWkOGQ8N+pvxDNZy4sJoGntAdLuLIRf17VBuZgRna7lUTmnTxkH8/FbMlbY4d6QcqZ4/HDppTXV6GeqXmz7lk7N90F/2E62pJgLcyplPUWoDKdqzD/WH0fejGEx4I3puPckFhMOIoLpOzUtQhGyXjajVA2bahPpJP0ET3ymQXw1E3qSyT+WF4gYlAhMI5B+PhWYthz6n3pZ6/aM15yNSuOD4I1NYXx15JUsB7SNQwSUMWXy2AlizjlJc3VVzuYM4zsSB3htcwfZNQyjHXRlo7Ws2g15aBhe+eSEATEc34UWgUGfWPIUWIDIPDOUV8MXnt2kKcJi06hOUvDt8dNjW1L/Dsa3RBOxegWoA7sPpuStJ1yQQPjacKNJCwi3DhLQ27wLqX/5xBwHfZIL47Ey8UrYd8Vy7b97DGtOfwDTXV70tyw9KXYjFkxPBiSoMNXLnwWLi/R1WRVCNjzwILv5C0A6w2WTP/5G6AF5sj6kTpnI6bKLTHUDOxGf0VGjzj4+RScKha0wmN7igXnn+BsD7Ai0CvvtZvdwc9dWisRYgjDUydrW9ZZrA6WCDKu410JOSX0cxkDtZ8WsU216xYo6t4uxZXBC0vSCgpE5fGo3ayM=
  template:
    metadata:
      name: speedscale-api-key
      namespace: agent-factory
